name: Graceful Gain
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Install Android Build Tools
        run: |
          mkdir -p $ANDROID_HOME
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip -O android-tools.zip
          unzip -q android-tools.zip -d $ANDROID_HOME
          echo "y" | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --install "platforms;android-29" "build-tools;29.0.3"
        env:
          ANDROID_HOME: ${{ runner.workspace }}/android-sdk

      - name: Install Aidl
        run: |
          sudo apt-get update
          sudo apt-get install -y aidl
          
      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - name: Cache Buildozer dependencies
        uses: actions/cache@v2
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
          
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: kivyapp/bin
